name: KochTrainer

options:
  bundleIdPrefix: com.kochtrainer
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1"  # iPhone only
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    # Versioning - MARKETING_VERSION is user-visible (App Store),
    # CURRENT_PROJECT_VERSION is build number (must increment for each TestFlight upload)
    MARKETING_VERSION: "0.9.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  KochTrainer:
    type: application
    platform: iOS
    sources:
      - path: KochTrainer
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kochtrainer.app
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Koch Trainer"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

  KochTrainerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: KochTrainerTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: KochTrainer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kochtrainer.tests
        GENERATE_INFOPLIST_FILE: YES

  KochTrainerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: KochTrainerUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: KochTrainer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kochtrainer.uitests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  KochTrainer:
    build:
      targets:
        KochTrainer: all
        KochTrainerTests: [test]
        KochTrainerUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - KochTrainerTests
        - KochTrainerUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
