name: KochTrainer

options:
  bundleIdPrefix: com.puntlabs
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  defaultConfig: Debug
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1"  # iPhone only
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    # Versioning - MARKETING_VERSION is user-visible (App Store),
    # CURRENT_PROJECT_VERSION is build number (must increment for each TestFlight upload)
    MARKETING_VERSION: "1.0.2"
    CURRENT_PROJECT_VERSION: "4"

targets:
  KochTrainer:
    type: application
    platform: iOS
    sources:
      - path: KochTrainer
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.puntlabs.kochtrainer
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: KochTrainer/Info.plist
      properties:
        CFBundleDisplayName: Koch Trainer
        CFBundleLocalizations:
          - en
          - en-GB
          - de
          - fr
          - es
          - it
        NSUserNotificationsUsageDescription: "Koch Trainer sends practice reminders and streak alerts to help you maintain a consistent learning schedule."
        ITSAppUsesNonExemptEncryption: false
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait

  KochTrainerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: KochTrainerTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: KochTrainer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.puntlabs.kochtrainer.tests
        GENERATE_INFOPLIST_FILE: YES

  KochTrainerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: KochTrainerUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: KochTrainer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.puntlabs.kochtrainer.uitests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  KochTrainer:
    build:
      targets:
        KochTrainer: all
        KochTrainerTests: [test]
        KochTrainerUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - KochTrainerTests
        - KochTrainerUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
